title: Kasozi Wilson
email: soziandwelewilson@gmail.com
baseurl: ""
prod_url: "http://kasoziwilson.com" # the base hostname & protocol for your site
dev_url: "http://localhost:4000"
twitter_username: KasoziWilson
github_username:  kwilson05

destination: _site

sass:
  sass_dir: _sass

author:
  name: "Kasozi A. Wilson"
  job: "Software Developer"
  bio: "I am a forever learner who luckily chose a career where innovation is not scarce.
  I attack most of my problems with some Java but HTML and CSS are becoming apart of my toolset too.
  Javascript will be my new tool to learn in 2017.

  If I am not programming, you'll see training for some triathlon/aquathon/race or eating pancakes. I can't forget PANCAKES!!

  Keep up with me by checking out my Blog, GitHub, StackOverflow, and Strava:"
  thumb: "Kasozi_Tri_2015.jpg"


collections:
  developments:

# Build settings
markdown: kramdown


#defaults:
 # scope:
  #  path: ""
   # type:
  #values:
#    layout: home



