title: Kasozi Wilson
email: soziandwelewilson@gmail.com
baseurl: ""
url: "http://kasoziwilson.com" # the base hostname & protocol for your site
twitter_username: KasoziWilson
github_username:  kwilson05

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

author:
  name: "Kasozi A. Wilson"
  job: "Software developer"
  bio: "I'm a forever learner who luckily chose a career where innovation is not scarce"
  thumb: "Kasozi_Tri_2015.jpg"

# Build settings
markdown: kramdown



