title: Kasozi Wilson
email: soziandwelewilson@gmail.com
baseurl: ""
prod_url: "http://kasoziwilson.com" # the base hostname & protocol for your site
dev_url: "http://localhost:4000"
twitter_username: KasoziWilson
github_username:  kwilson05

destination: _site

author:
  name: "Kasozi A. Wilson"
  job: "Software developer"
  bio: "I'm a forever learner who luckily chose a career where innovation is not scarce"
  thumb: "Kasozi_Tri_2015.jpg"


collections:
  developments:

# Build settings
markdown: kramdown


#defaults:
 # scope:
  #  path: ""
   # type:
  #values:
#    layout: home



