# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kasozi Wilson
email: soziandwelewilson@gmail.com
baseurl: ""
prod_url: "http://kasoziwilson.com" # the base hostname & protocol for your site
dev_url: "http://localhost:4000"
twitter_username: KasoziWilson
github_username:  kwilson05

destination: _site

author:
  name: "Kasozi Wilson"
  job: "Software developer"
  bio: "I'm a forever learner who luckily chose a career where innovation is not scarce"
  thumb: "Kasozi_Tri_2015.jpg"


collections:
  developments:

# Build settings
markdown: kramdown


#defaults:
 # scope:
  #  path: ""
   # type:
  #values:
#    layout: home



